#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Branslekollen.Droid.Resource", IsApplication=true)]

namespace Branslekollen.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLStorage.Resource.String.ApplicationName = global::Branslekollen.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::Branslekollen.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050004
			public const int my_accent = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int my_primary = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int my_primary_dark = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int my_text_color = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int my_validation_error = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int my_white = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_account_circle_white_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_add_circle_white_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_add_white_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_delete_white_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_equalizer_white_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_local_gas_station_white_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_save_white_24dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int no_connection = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int no_connection_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int road = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080019
			public const int BottomNavigationFragment = 2131230745;
			
			// aapt resource value: 0x7f080003
			public const int BottomNavigationMenuItemProfile = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int BottomNavigationMenuItemRefuelings = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int BottomNavigationMenuItemStatistics = 2131230721;
			
			// aapt resource value: 0x7f080015
			public const int DateTextView = 2131230741;
			
			// aapt resource value: 0x7f08000a
			public const int FuelTypeDieselRadioButton = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int FuelTypePetrolRadioButton = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int FuelTypeRadioGroup = 2131230728;
			
			// aapt resource value: 0x7f08000d
			public const int GettingStartedButton = 2131230733;
			
			// aapt resource value: 0x7f08001b
			public const int MenuItemAdd = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int MenuItemDelete = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int MenuItemSave = 2131230749;
			
			// aapt resource value: 0x7f080014
			public const int RefuelingBottomNavigationFragment = 2131230740;
			
			// aapt resource value: 0x7f08000e
			public const int RefuelingDateEditText = 2131230734;
			
			// aapt resource value: 0x7f080013
			public const int RefuelingFullTankSwitch = 2131230739;
			
			// aapt resource value: 0x7f080012
			public const int RefuelingOdometerEditText = 2131230738;
			
			// aapt resource value: 0x7f08000f
			public const int RefuelingPriceEditText = 2131230735;
			
			// aapt resource value: 0x7f080011
			public const int RefuelingTotalPriceEditText = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int RefuelingVolumeEditText = 2131230736;
			
			// aapt resource value: 0x7f080018
			public const int RefuelingsList = 2131230744;
			
			// aapt resource value: 0x7f080004
			public const int Toolbar = 2131230724;
			
			// aapt resource value: 0x7f080017
			public const int TotalPriceTextView = 2131230743;
			
			// aapt resource value: 0x7f080006
			public const int VehicleNameEditText = 2131230726;
			
			// aapt resource value: 0x7f080016
			public const int VolumeTextView = 2131230742;
			
			// aapt resource value: 0x7f080000
			public const int bottom_navigation = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int fuelTypeLabel = 2131230727;
			
			// aapt resource value: 0x7f08001a
			public const int imageViewGettingVehicles = 2131230746;
			
			// aapt resource value: 0x7f08000b
			public const int textView1 = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int textView2 = 2131230732;
			
			// aapt resource value: 0x7f080005
			public const int vehicleNameLabel = 2131230725;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BottomNavigation = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreateVehicle = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Refueling = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RefuelingRowLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Refuelings = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Splash = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Toolbar = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int TopMenuAdd = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int TopMenuSave = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040011
			public const int add = 2130968593;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f04000b
			public const int create_vehicle = 2130968587;
			
			// aapt resource value: 0x7f040003
			public const int dashboard = 2130968579;
			
			// aapt resource value: 0x7f040014
			public const int date = 2130968596;
			
			// aapt resource value: 0x7f040013
			public const int delete = 2130968595;
			
			// aapt resource value: 0x7f040019
			public const int did_you_refill_completely = 2130968601;
			
			// aapt resource value: 0x7f04001f
			public const int error_adding_refueling = 2130968607;
			
			// aapt resource value: 0x7f04000e
			public const int fuel_type = 2130968590;
			
			// aapt resource value: 0x7f040010
			public const int fuel_type_diesel = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int fuel_type_petrol = 2130968591;
			
			// aapt resource value: 0x7f04000a
			public const int get_started = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int getting_your_vehicles = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int history = 2130968582;
			
			// aapt resource value: 0x7f040018
			public const int odometer = 2130968600;
			
			// aapt resource value: 0x7f040015
			public const int price = 2130968597;
			
			// aapt resource value: 0x7f040007
			public const int profile = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int refuelings = 2130968581;
			
			// aapt resource value: 0x7f040012
			public const int save = 2130968594;
			
			// aapt resource value: 0x7f040004
			public const int statistics = 2130968580;
			
			// aapt resource value: 0x7f040017
			public const int total_price = 2130968599;
			
			// aapt resource value: 0x7f04001b
			public const int validation_error_date = 2130968603;
			
			// aapt resource value: 0x7f04001e
			public const int validation_error_odometer = 2130968606;
			
			// aapt resource value: 0x7f04001c
			public const int validation_error_price = 2130968604;
			
			// aapt resource value: 0x7f04001a
			public const int validation_error_vehicle_name = 2130968602;
			
			// aapt resource value: 0x7f04001d
			public const int validation_error_volume = 2130968605;
			
			// aapt resource value: 0x7f04000c
			public const int vehicle_name = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int vehicle_name_hint = 2130968589;
			
			// aapt resource value: 0x7f040016
			public const int volume = 2130968598;
			
			// aapt resource value: 0x7f040009
			public const int welcome = 2130968585;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060003
			public const int BranslekollenTheme = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int MyCustomTheme_NoActionBar = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int MyCustomTheme_NoConnection = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int MyCustomTheme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
