#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Branslekollen.Droid.Resource", IsApplication=true)]

namespace Branslekollen.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLStorage.Resource.String.ApplicationName = global::Branslekollen.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::Branslekollen.Droid.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fade_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_down = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_up = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060004
			public const int my_accent = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int my_primary = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int my_primary_dark = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int my_text_color = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int my_validation_error = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int my_white = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_account_circle_white_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_add_circle_white_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_add_white_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_delete_white_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_equalizer_white_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_local_gas_station_white_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_save_white_24dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int no_connection = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int no_connection_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int road = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000c
			public const int BottomNavigationFragment = 2131296268;
			
			// aapt resource value: 0x7f090003
			public const int BottomNavigationMenuItemProfile = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int BottomNavigationMenuItemRefuelings = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int BottomNavigationMenuItemStatistics = 2131296257;
			
			// aapt resource value: 0x7f090013
			public const int DateTextView = 2131296275;
			
			// aapt resource value: 0x7f09000b
			public const int DeleteAllVehiclesButton = 2131296267;
			
			// aapt resource value: 0x7f09000a
			public const int FuelTypeDieselRadioButton = 2131296266;
			
			// aapt resource value: 0x7f090009
			public const int FuelTypePetrolRadioButton = 2131296265;
			
			// aapt resource value: 0x7f090008
			public const int FuelTypeRadioGroup = 2131296264;
			
			// aapt resource value: 0x7f090019
			public const int GettingStartedButton = 2131296281;
			
			// aapt resource value: 0x7f09001b
			public const int MenuItemAdd = 2131296283;
			
			// aapt resource value: 0x7f09001c
			public const int MenuItemDelete = 2131296284;
			
			// aapt resource value: 0x7f09001d
			public const int MenuItemSave = 2131296285;
			
			// aapt resource value: 0x7f09000d
			public const int RefuelingDateEditText = 2131296269;
			
			// aapt resource value: 0x7f090012
			public const int RefuelingFullTankSwitch = 2131296274;
			
			// aapt resource value: 0x7f090011
			public const int RefuelingOdometerEditText = 2131296273;
			
			// aapt resource value: 0x7f09000e
			public const int RefuelingPriceEditText = 2131296270;
			
			// aapt resource value: 0x7f090010
			public const int RefuelingTotalPriceEditText = 2131296272;
			
			// aapt resource value: 0x7f09000f
			public const int RefuelingVolumeEditText = 2131296271;
			
			// aapt resource value: 0x7f090016
			public const int RefuelingsList = 2131296278;
			
			// aapt resource value: 0x7f09001a
			public const int StatisticsAverageConsumptionTextView = 2131296282;
			
			// aapt resource value: 0x7f090004
			public const int Toolbar = 2131296260;
			
			// aapt resource value: 0x7f090015
			public const int TotalPriceTextView = 2131296277;
			
			// aapt resource value: 0x7f090006
			public const int VehicleNameEditText = 2131296262;
			
			// aapt resource value: 0x7f090014
			public const int VolumeTextView = 2131296276;
			
			// aapt resource value: 0x7f090000
			public const int bottom_navigation = 2131296256;
			
			// aapt resource value: 0x7f090007
			public const int fuelTypeLabel = 2131296263;
			
			// aapt resource value: 0x7f090017
			public const int textView1 = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int textView2 = 2131296280;
			
			// aapt resource value: 0x7f090005
			public const int vehicleNameLabel = 2131296261;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BottomNavigation = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreateVehicle = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Profile = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Refueling = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RefuelingRowLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Refuelings = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Splash = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Statistics = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Toolbar = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int TopMenuAdd = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int TopMenuSave = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050012
			public const int add = 2131034130;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f05000c
			public const int create_vehicle = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int dashboard = 2131034115;
			
			// aapt resource value: 0x7f050016
			public const int date = 2131034134;
			
			// aapt resource value: 0x7f050014
			public const int delete = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int delete_all_vehicles = 2131034133;
			
			// aapt resource value: 0x7f05001b
			public const int did_you_refill_completely = 2131034139;
			
			// aapt resource value: 0x7f050021
			public const int error_adding_refueling = 2131034145;
			
			// aapt resource value: 0x7f05000f
			public const int fuel_type = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int fuel_type_diesel = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int fuel_type_petrol = 2131034128;
			
			// aapt resource value: 0x7f05000b
			public const int get_started = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int getting_your_vehicles = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int history = 2131034119;
			
			// aapt resource value: 0x7f050022
			public const int not_enough_refuelings_to_calculate_average = 2131034146;
			
			// aapt resource value: 0x7f05001a
			public const int odometer = 2131034138;
			
			// aapt resource value: 0x7f050017
			public const int price = 2131034135;
			
			// aapt resource value: 0x7f050008
			public const int profile = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int refueling = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int refuelings = 2131034117;
			
			// aapt resource value: 0x7f050013
			public const int save = 2131034131;
			
			// aapt resource value: 0x7f050004
			public const int statistics = 2131034116;
			
			// aapt resource value: 0x7f050019
			public const int total_price = 2131034137;
			
			// aapt resource value: 0x7f05001d
			public const int validation_error_date = 2131034141;
			
			// aapt resource value: 0x7f050020
			public const int validation_error_odometer = 2131034144;
			
			// aapt resource value: 0x7f05001e
			public const int validation_error_price = 2131034142;
			
			// aapt resource value: 0x7f05001c
			public const int validation_error_vehicle_name = 2131034140;
			
			// aapt resource value: 0x7f05001f
			public const int validation_error_volume = 2131034143;
			
			// aapt resource value: 0x7f05000d
			public const int vehicle_name = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int vehicle_name_hint = 2131034126;
			
			// aapt resource value: 0x7f050018
			public const int volume = 2131034136;
			
			// aapt resource value: 0x7f05000a
			public const int welcome = 2131034122;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int BranslekollenTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
